### PR TITLE
[Feature] Updated to use cashaddr addresses

### PR DESCRIPTION
**Pull request by zquestz**
I have updated everything to present cashaddr style addresses. The only tab I didn't update was the Vanity Wallet, since it requires the old format, and is pretty neat.

* All QR codes should now use cashaddr.
* The paper wallet discards the 'bitcoincash:' prefix to save space, but the QR codes are for the full address.
* Updated BCH donation addresses to cashaddr style.
* Removed prefix from private key QR codes to fix sweeps.

Please review, would love to get this rockin.

NOTE: Using https://github.com/bitcoincashjs/bchaddrjs for the conversions.

### CODE REVIEW

**Comment by DesWurstes** [comment]
Hi, I'm working on a Pull Request to cashaddrjs. It'll remove the big number dependency, and the source code will be much smaller. Would you be able to update this file if my Pull Request gets merged?

**Comment by zquestz** [comment]
I am open to using a more lightweight library. I think this should merge and we can always update it later. 😀

**Comment by zquestz** [comment]
@theantnest @daftspunk please review!

**Comment by CreativeName4** [comment]
Reviewed, looks good! thanks @zquestz !!

**Comment by imaginaryusername** [comment]
Can confirm, private keys are now good to scan using Bitcoin.com wallet. Tested in single key, paper wallet.

**Comment by zquestz** [comment]
Going to merge this, thanks for the reviews folks =)

**Review by wizzelman801 — COMMENTED** [review]
🫣

**Review by wizzelman801 — COMMENTED** [review]
🤗

**Pull request merged**
